//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AnalyticsService.Database.Queries {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Query {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Query() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AnalyticsService.Database.Queries.Query", typeof(Query).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DELETE FROM DLQ WHERE Id = @Id.
        /// </summary>
        internal static string DeleteDlqItems {
            get {
                return ResourceManager.GetString("DeleteDlqItems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT
        ///    b.Id,
        ///    b.StartDate,
        ///    b.EndDate,
        ///    b.NumberOfDocuments,
        ///    b.RunTime,
        ///    b.Status
        ///FROM
        ///    BatchStats as b.
        /// </summary>
        internal static string GetBatchStats {
            get {
                return ResourceManager.GetString("GetBatchStats", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT
        ///    d.Id,
        ///    d.Endpoint,
        ///    d.RequestData
        ///FROM
        ///    DLQ as d.
        /// </summary>
        internal static string GetDlqItems {
            get {
                return ResourceManager.GetString("GetDlqItems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INSERT INTO
        ///    BatchStats
        ///VALUES (@Id, @StartDate, @EndDate, @NumberOfDocuments, @RunTime, @Status, @WorkflowId, @Created).
        /// </summary>
        internal static string InsertBatchStat {
            get {
                return ResourceManager.GetString("InsertBatchStat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INSERT INTO
        ///    DLQ
        ///VALUES (@Id, @Endpoint, @RequestData, @Source, @DateAdded).
        /// </summary>
        internal static string InsertDlqTopic {
            get {
                return ResourceManager.GetString("InsertDlqTopic", resourceCulture);
            }
        }
    }
}
