BEGIN;

CREATE TABLE "BatchStats" (
    "Id" UUID PRIMARY KEY,
    "StartDate" TIMESTAMP WITH TIME ZONE NOT NULL,
    "EndDate" TIMESTAMP WITH TIME ZONE NOT NULL,
    "NumberOfDocuments" INTEGER NOT NULL,
    "RunTime" INTERVAL NOT NULL,
    "Status" SMALLINT NOT NULL,
    "WorkflowId" UUID NOT NULL,
    "Created" TIMESTAMP WITH TIME ZONE NOT NULL
);

CREATE TABLE "DLQ" (
    "Id" UUID PRIMARY KEY,
    "Endpoint" VARCHAR(255) NOT NULL,
    "RequestData" BYTEA NOT NULL,
    "Source" VARCHAR(128) NOT NULL,
    "DateAdded" TIMESTAMP WITH TIME ZONE NOT NULL
);

COMMIT;